name: Epic Issue Template
description: Template for creating a new Epic
title: "📚 EPIC: <Brief description of the epic>"
labels: ["epic"]
body:
  - type: markdown
    attributes:
      value: |
        ## Epic Description
        Describe the goal and context of this epic.
  - type: textarea
    id: epic-description
    attributes:
      label: Epic Description
      placeholder: "Provide a clear and concise description of the epic."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## User Stories
        List the user stories that are part of this epic or link to existing issues.
  - type: textarea
    id: user-stories
    attributes:
      label: User Stories
      placeholder: "List the user stories or link to existing issues that are part of this epic."
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Additional Notes
        Add any additional information, links, or references that are relevant to this epic.
  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      placeholder: "Provide any additional information, links, or references."
    validations:
      required: false
